'use client';

export interface ExportColumn { header: string; key: string; }
export interface SummaryItem  { label: string;  value: string; }

// ─── PDF ─────────────────────────────────────────────────────────────────────
export const exportPDF = async (
  reportTitle: string,
  summary: SummaryItem[],
  columns: ExportColumn[],
  rows: Record<string, unknown>[],
  filename: string
) => {
  const { default: jsPDF }   = await import('jspdf');
  const { default: autoTable } = await import('jspdf-autotable');

  const doc  = new jsPDF();
  const BLUE = [30, 58, 138] as [number, number, number];
  const LGRY = [245, 247, 250] as [number, number, number];

  // Header bar
  doc.setFillColor(...BLUE);
  doc.rect(0, 0, 210, 22, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(15); doc.setFont('helvetica', 'bold');
  doc.text('AE Samonte Merchandise', 14, 10);
  doc.setFontSize(8);  doc.setFont('helvetica', 'normal');
  doc.text('ALAIN E. SAMONTE - Prop.  |  VAT Reg. TIN: 263-884-036-00000', 14, 17);
  doc.setTextColor(0, 0, 0);

  // Title + date
  doc.setFontSize(13); doc.setFont('helvetica', 'bold');
  doc.text(reportTitle, 14, 31);
  doc.setFontSize(9);  doc.setFont('helvetica', 'normal');
  doc.setTextColor(120);
  doc.text(`Generated: ${new Date().toLocaleDateString('en-PH', { year: 'numeric', month: 'long', day: 'numeric' })}`, 14, 37);
  doc.setTextColor(0);

  // Summary table
  doc.setFontSize(9); doc.setFont('helvetica', 'bold');
  doc.text('SUMMARY', 14, 46);
  autoTable(doc, {
    startY: 49,
    head: [],
    body: summary.map(s => [s.label, s.value]),
    theme: 'grid',
    styles: { fontSize: 9, cellPadding: 2.5 },
    columnStyles: {
      0: { fontStyle: 'bold', cellWidth: 65, fillColor: LGRY },
      1: { cellWidth: 50 },
    },
    tableWidth: 115,
  });

  // Data table
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const afterSummary = (doc as any).lastAutoTable.finalY + 8;
  doc.setFontSize(9); doc.setFont('helvetica', 'bold');
  doc.text('DATA', 14, afterSummary);

  autoTable(doc, {
    startY: afterSummary + 3,
    head: [columns.map(c => c.header)],
    body: rows.map(row => columns.map(c => String(row[c.key] ?? ''))),
    theme: 'grid',
    headStyles: { fillColor: BLUE, textColor: 255, fontStyle: 'bold', fontSize: 8 },
    styles: { fontSize: 8, cellPadding: 2 },
    alternateRowStyles: { fillColor: LGRY },
  });

  // Footer
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const finalY = (doc as any).lastAutoTable.finalY + 8;
  doc.setFontSize(8); doc.setTextColor(160);
  doc.text('Generated by AE Samonte System', 14, finalY);
  doc.text(`Total records: ${rows.length}`, 196, finalY, { align: 'right' });

  doc.save(`${filename}.pdf`);
};

// ─── EXCEL ───────────────────────────────────────────────────────────────────
export const exportExcel = async (
  reportTitle: string,
  summary: SummaryItem[],
  columns: ExportColumn[],
  rows: Record<string, unknown>[],
  filename: string
) => {
  const XLSX = await import('xlsx');

  const wb = XLSX.utils.book_new();
  const sheetData: unknown[][] = [];

  // Header rows
  sheetData.push(['AE Samonte Merchandise']);
  sheetData.push(['ALAIN E. SAMONTE - Prop.  |  VAT Reg. TIN: 263-884-036-00000']);
  sheetData.push([reportTitle]);
  sheetData.push([`Generated: ${new Date().toLocaleDateString('en-PH', { year: 'numeric', month: 'long', day: 'numeric' })}`]);
  sheetData.push([]);

  // Summary
  sheetData.push(['SUMMARY']);
  summary.forEach(s => sheetData.push([s.label, s.value]));
  sheetData.push([]);

  // Data
  sheetData.push(['DATA']);
  sheetData.push(columns.map(c => c.header));
  rows.forEach(row => sheetData.push(columns.map(c => row[c.key] ?? '')));

  const ws = XLSX.utils.aoa_to_sheet(sheetData);

  // Column widths
  ws['!cols'] = columns.map(c => ({ wch: Math.max(c.header.length + 4, 16) }));

  XLSX.utils.book_append_sheet(wb, ws, reportTitle.slice(0, 31));
  XLSX.writeFile(wb, `${filename}.xlsx`);
};

// ─── CSV ─────────────────────────────────────────────────────────────────────
export const exportCSV = (
  reportTitle: string,
  summary: SummaryItem[],
  columns: ExportColumn[],
  rows: Record<string, unknown>[],
  filename: string
) => {
  const wrap = (v: string) =>
    v.includes(',') || v.includes('"') || v.includes('\n')
      ? `"${v.replace(/"/g, '""')}"`
      : v;

  const lines = [
    'AE Samonte Merchandise',
    `Report: ${reportTitle}`,
    `Generated: ${new Date().toISOString()}`,
    `Total Records: ${rows.length}`,
    '',
    'SUMMARY',
    ...summary.map(s => `${wrap(s.label)},${wrap(s.value)}`),
    '',
    'DATA',
    columns.map(c => wrap(c.header)).join(','),
    ...rows.map(row => columns.map(c => wrap(String(row[c.key] ?? ''))).join(',')),
  ];

  const blob = new Blob([lines.join('\n')], { type: 'text/csv;charset=utf-8;' });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement('a');
  a.href = url;
  a.setAttribute('download', `${filename}.csv`);
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};
